name: Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish (e.g., v0.1.0). If empty, uses latest release tag."
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Use release tag
        id: vars
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            TAG="${{ github.event.release.tag_name }}"
          else
            TAG="${{ github.event.inputs.tag }}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Using tag: $TAG"

      - name: Verify tag matches package.json version
        if: steps.vars.outputs.tag != ''
        shell: bash
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          TAG="${{ steps.vars.outputs.tag }}"
          if [[ "v$PKG_VERSION" != "$TAG" ]]; then
            echo "Tag $TAG does not match package.json version v$PKG_VERSION" >&2
            exit 1
          fi

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ -z "$NODE_AUTH_TOKEN" ]; then
            echo "NPM_TOKEN secret is not set" >&2
            exit 1
          fi
          npm publish --access public

